package login_register;


import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import login_register.Connct;
import login_register.listOfUser;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author camayma_sd2081
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        
        //center form
        this.setLocationRelativeTo(null);
        
        Border jpanel_title_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        //set the border to the jPanel_title
        jPanel_title.setBorder(jpanel_title_border);
        
        //create a black border for the global panel
        Border global_panel_border = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
       jPanel1.setBorder(global_panel_border);
        
        //create a black border for the close & minimize jlabels
        Border jlabelborder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_minimize.setBorder(jlabelborder);
        jLabel_close.setBorder(jlabelborder);
        
        //create border for the username and password field
        Border field_border = BorderFactory.createMatteBorder(1, 3, 1, 1, Color.white);
        jTextField_FirstName.setBorder(field_border);
        jTextField_MiddleName.setBorder(field_border);
        jTextField_LastName.setBorder(field_border);
        jTextField_Email.setBorder(field_border);
        jPasswordField_Password.setBorder(field_border);
        jPasswordField_reTypePassword.setBorder(field_border);
        jTextField_Number.setBorder(field_border);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField_FirstName = new javax.swing.JTextField();
        jPasswordField_reTypePassword = new javax.swing.JPasswordField();
        jButton_Register = new javax.swing.JButton();
        jPasswordField_Password = new javax.swing.JPasswordField();
        jLabel_middlename = new javax.swing.JLabel();
        jLabel_lastname = new javax.swing.JLabel();
        jLabel_email = new javax.swing.JLabel();
        jLabel_password = new javax.swing.JLabel();
        jLabel_firstname = new javax.swing.JLabel();
        jLabel_retypePassword = new javax.swing.JLabel();
        jTextField_Number = new javax.swing.JTextField();
        jTextField_MiddleName = new javax.swing.JTextField();
        jTextField_LastName = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jLabel_number = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jPanel_title = new javax.swing.JPanel();
        jLabel_Register = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jTextField_FirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_FirstName.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_FirstName.setText("firstname");
        jTextField_FirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_FirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_FirstNameFocusLost(evt);
            }
        });
        jTextField_FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FirstNameActionPerformed(evt);
            }
        });

        jPasswordField_reTypePassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_reTypePassword.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_reTypePassword.setText("Password");
        jPasswordField_reTypePassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_reTypePasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_reTypePasswordFocusLost(evt);
            }
        });

        jButton_Register.setBackground(new java.awt.Color(235, 47, 6));
        jButton_Register.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton_Register.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Register.setText("Register");
        jButton_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_RegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_RegisterMouseExited(evt);
            }
        });
        jButton_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegisterActionPerformed(evt);
            }
        });

        jPasswordField_Password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_Password.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_Password.setText("Password");
        jPasswordField_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_PasswordFocusLost(evt);
            }
        });

        jLabel_middlename.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_middlename.setText("Middle Name:");

        jLabel_lastname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_lastname.setText("Last Name:");

        jLabel_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_email.setText("Email:");

        jLabel_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_password.setText("Password:");

        jLabel_firstname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_firstname.setText(" First Name:");

        jLabel_retypePassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_retypePassword.setText("Re-type Password:");

        jTextField_Number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Number.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_Number.setText("number");
        jTextField_Number.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_NumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_NumberFocusLost(evt);
            }
        });
        jTextField_Number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_NumberKeyTyped(evt);
            }
        });

        jTextField_MiddleName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_MiddleName.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_MiddleName.setText("middlename");
        jTextField_MiddleName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_MiddleNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_MiddleNameFocusLost(evt);
            }
        });
        jTextField_MiddleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_MiddleNameActionPerformed(evt);
            }
        });

        jTextField_LastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_LastName.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_LastName.setText("lastname");
        jTextField_LastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_LastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_LastNameFocusLost(evt);
            }
        });

        jTextField_Email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Email.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_Email.setText("email");
        jTextField_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_EmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_EmailFocusLost(evt);
            }
        });

        jLabel_number.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_number.setText("Number:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel_firstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel_middlename, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel_email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_lastname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_retypePassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPasswordField_reTypePassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_Number, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_MiddleName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_LastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextField_Email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPasswordField_Password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_firstname, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jTextField_FirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_middlename, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_MiddleName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_lastname, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jTextField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Email, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_password, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField_Password, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_retypePassword, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jPasswordField_reTypePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Number, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel_number, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90)
                .addComponent(jButton_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jLabel_minimize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_minimize.setText(" -");
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
        });

        jLabel_close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_close.setText("  x");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseExited(evt);
            }
        });

        jPanel_title.setBackground(new java.awt.Color(0, 0, 204));

        jLabel_Register.setBackground(new java.awt.Color(255, 204, 255));
        jLabel_Register.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_Register.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Register.setText("Register");

        javax.swing.GroupLayout jPanel_titleLayout = new javax.swing.GroupLayout(jPanel_title);
        jPanel_title.setLayout(jPanel_titleLayout);
        jPanel_titleLayout.setHorizontalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel_Register)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel_titleLayout.setVerticalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addComponent(jLabel_Register)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_FirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_FirstNameFocusGained
        // clear the textfield on focus if the text is "username"
        if(jTextField_FirstName.getText().trim().toLowerCase().equals("firstname")){
            jTextField_FirstName.setText("");
            jTextField_FirstName.setForeground(Color.black);
        }
        //set a color border to the jlabelIcon
//        Border jlabel_icon = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);

//        jLabel_username.setBorder(jlabel_icon);
    }//GEN-LAST:event_jTextField_FirstNameFocusGained

    private void jTextField_FirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_FirstNameFocusLost

        //if the password field is equal to username or empty
        //we will set the "username"text in the field
        //on focus lost event
//        if(jTextField_FirstName.getText().trim().equals("") ||
//            jTextField_FirstName.getText().trim().toLowerCase().equals("firstname"))
//        {
//            jTextField_FirstName.setText("firstname");
//            jTextField_FirstName.setForeground(new  Color(153, 153, 153)) ;
//        }
        //create a border with the color of thr parent jpanel  for the icons  label to remove the move
//        Border label_icons_border = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(153,153,153));
//        jLabel_username.setBorder(label_icons_border);

    }//GEN-LAST:event_jTextField_FirstNameFocusLost

    private void jPasswordField_reTypePasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_reTypePasswordFocusGained
        // clear the textfield on focus if the text is "password"

        //get the password text
        String repass = String.valueOf(jPasswordField_reTypePassword.getPassword());

        if(repass.trim().toLowerCase().equals("password")){
            jPasswordField_reTypePassword.setText("");
            jPasswordField_reTypePassword.setForeground(Color.black);
        }
        //set a color border to the jlabelIcon
//        Border jpassword_icon = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);

//        jLabel_password.setBorder(jpassword_icon);
    }//GEN-LAST:event_jPasswordField_reTypePasswordFocusGained

    private void jPasswordField_reTypePasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_reTypePasswordFocusLost
        //if the username field is equal to password or empty
        //we will set the "password"text in the field
        //on focus lost event
//        String repass = String.valueOf(jPasswordField_reTypePassword.getPassword());
//        if(repass.trim().equals("") ||
//            repass.trim().toLowerCase().equals("password"))
//        {
//            jPasswordField_reTypePassword.setText("password");
//            jPasswordField_reTypePassword.setForeground(new  Color(153, 153, 153)) ;
//        }
        //create a border with the color of thr parent jpanel  for the icons  label to remove the move
//        Border label_icons_border = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(153,153,153));
//        jLabel_password.setBorder(label_icons_border);
    }//GEN-LAST:event_jPasswordField_reTypePasswordFocusLost

    private void jButton_RegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RegisterMouseEntered
        // set jbutton background
        jButton_Register.setBackground(new Color(225,20,2));
    }//GEN-LAST:event_jButton_RegisterMouseEntered

    private void jButton_RegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_RegisterMouseExited
        // set jbutton background
        jButton_Register.setBackground(new Color(235,47,6));

    }//GEN-LAST:event_jButton_RegisterMouseExited

    private void jButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegisterActionPerformed
        
     String fname = jTextField_FirstName.getText();
     String mname = jTextField_MiddleName.getText();
     String lname = jTextField_LastName.getText();
     String email = jTextField_Email.getText();
     String pnumber = jTextField_Number.getText();
     String pass1 = String.valueOf(jPasswordField_Password.getPassword());
     String pass2 = String.valueOf(jPasswordField_reTypePassword.getPassword());
     
     if (verifyFields())
     {
         if (!checkUsername(email))
         {
             PreparedStatement ps;
             ResultSet rs;
             String registerUserQuery = "INSERT INTO `users`(`First Name`, `Middle Name`, `Last Name`, `Email`, `Password`, `Number`) VALUES (?,?,?,?,?,?)";
             
             try {
                 ps = Connct.getConnection().prepareStatement(registerUserQuery);
                 ps.setString(1, fname);
                 ps.setString(2, mname);
                 ps.setString(3, lname);
                 ps.setString(4, email);
                 ps.setString(5, pass1);
                 ps.setString(6, pnumber);
                 
                 
//                 ps.setString(7, pass2);
                 
//                 ps.setNull(7, java.sql.Types.NULL);
                 
                if(ps.executeUpdate() != 0)
                {
                    JOptionPane.showMessageDialog(null , "Youre account has been created");  
                }else {
                    JOptionPane.showMessageDialog(null , "ERROR ! Please fill up everything");
             }
              
                 
                 
                 
             } catch (SQLException ex) {
                 Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
             }
             
         }
     }

    }//GEN-LAST:event_jButton_RegisterActionPerformed

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
        Border jlabelborder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_minimize.setBorder(jlabelborder);
        jLabel_minimize.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
        Border jlabelborder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_minimize.setBorder(jlabelborder);
        jLabel_minimize.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseEntered
        Border jlabelborder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
        jLabel_close.setBorder(jlabelborder);
        jLabel_close.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_closeMouseEntered

    private void jLabel_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseExited
        Border jlabelborder = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.black);
        jLabel_close.setBorder(jlabelborder);
        jLabel_close.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_closeMouseExited

    private void jPasswordField_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordFocusGained
        String pass = String.valueOf(jPasswordField_Password.getPassword());
        if(pass.trim().toLowerCase().equals("password")){
            jPasswordField_Password.setText("");
            jPasswordField_Password.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordField_PasswordFocusGained

    private void jPasswordField_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_PasswordFocusLost
//         String pass = String.valueOf(jPasswordField_Password.getPassword());
//        if(pass.trim().equals("") ||
//            pass.trim().toLowerCase().equals("password"))
//        {
//            jPasswordField_Password.setText("password");
//            jPasswordField_Password.setForeground(new  Color(153, 153, 153)) ;
//        }
    }//GEN-LAST:event_jPasswordField_PasswordFocusLost

    private void jTextField_NumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_NumberFocusGained
         if(jTextField_Number.getText().trim().toLowerCase().equals("number")){
            jTextField_Number.setText("");
            jTextField_Number.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_NumberFocusGained

    private void jTextField_NumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_NumberFocusLost
//        if(jTextField_Number.getText().trim().equals("") ||
//            jTextField_Number.getText().trim().toLowerCase().equals("number"))
//        {
//            jTextField_Number.setText("number");
//            jTextField_Number.setForeground(new  Color(153, 153, 153)) ;
//        }
    }//GEN-LAST:event_jTextField_NumberFocusLost

    private void jTextField_MiddleNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_MiddleNameFocusGained
          if(jTextField_MiddleName.getText().trim().toLowerCase().equals("middlename")){
            jTextField_MiddleName.setText("");
            jTextField_MiddleName.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_MiddleNameFocusGained

    private void jTextField_MiddleNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_MiddleNameFocusLost
//        if(jTextField_MiddleName.getText().trim().equals("") ||
//            jTextField_MiddleName.getText().trim().toLowerCase().equals("middlename"))
//        {
//            jTextField_MiddleName.setText("middlename");
//            jTextField_MiddleName.setForeground(new  Color(153, 153, 153)) ;
//        }
    }//GEN-LAST:event_jTextField_MiddleNameFocusLost

    private void jTextField_MiddleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_MiddleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_MiddleNameActionPerformed

    private void jTextField_LastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_LastNameFocusGained
         if(jTextField_LastName.getText().trim().toLowerCase().equals("lastname")){
            jTextField_LastName.setText("");
            jTextField_LastName.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_LastNameFocusGained

    private void jTextField_LastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_LastNameFocusLost
//       if(jTextField_LastName.getText().trim().equals("") ||
//            jTextField_LastName.getText().trim().toLowerCase().equals("lastname"))
//        {
//            jTextField_LastName.setText("lastname");
//            jTextField_LastName.setForeground(new  Color(153, 153, 153)) ;
//        }
    }//GEN-LAST:event_jTextField_LastNameFocusLost

    private void jTextField_EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_EmailFocusGained
        if(jTextField_Email.getText().trim().toLowerCase().equals("email")){
            jTextField_Email.setText("");
            jTextField_Email.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_EmailFocusGained

    private void jTextField_EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_EmailFocusLost
//        if(jTextField_Email.getText().trim().equals("") ||
//            jTextField_Email.getText().trim().toLowerCase().equals("email"))
//        {
//            jTextField_Email.setText("email");
//            jTextField_Email.setForeground(new  Color(153, 153, 153)) ;
//        }
    }//GEN-LAST:event_jTextField_EmailFocusLost

    private void jTextField_FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FirstNameActionPerformed

    private void jTextField_NumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NumberKeyTyped
       // allow only numbers
        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_NumberKeyTyped

    public boolean verifyFields()
    {
        String fname = jTextField_FirstName.getText();
        String mname = jTextField_MiddleName.getText();
        String lname = jTextField_LastName.getText();
        String email = jTextField_Email.getText();
        String pnumber = jTextField_Number.getText();
        String pass1 = String.valueOf(jPasswordField_Password.getPassword());
        String pass2 = String.valueOf(jPasswordField_reTypePassword.getPassword());
        
        
        //check empty fields
        if(fname.trim().equals("")|| mname.trim().equals("")|| email.trim().equals("") || lname.trim().equals("") || pnumber.trim().equals("") || pass1.trim().equals("") || pass2.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "One or More Fields are Empty","Empty Fields",2);
            return false;
            
        }
        // check if the two password are equals
        else if (!pass1.equals(pass2)){
        JOptionPane.showMessageDialog(null, "Password Doesn't Match","Confirm Password",2);
        return false;
        }
        //if everyting is ok
        else{
                return true;
        }
        
        
    }
    //create a function to check if the entered username already exist in the database
    public boolean checkUsername(String username){
        PreparedStatement st ;
        ResultSet rs;
        boolean username_exist = false;
        String query = "SELECT * FROM `users` WHERE `Email` = ? ";
        
        try {
            st = Connct.getConnection().prepareStatement(query);
            st.setString(1,username);
            rs = st.executeQuery();
            
            if(rs.next()) 
            {
                username_exist = false;
                JOptionPane.showMessageDialog(null, "This username is already taken , choose another One", "Username Failed", 2);
                
            }   
            
            
        } catch (SQLException ex) {
            Logger.getLogger(LogInFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        return username_exist;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Register;
    private javax.swing.JLabel jLabel_Register;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_firstname;
    private javax.swing.JLabel jLabel_lastname;
    private javax.swing.JLabel jLabel_middlename;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_number;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_retypePassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_title;
    private javax.swing.JPasswordField jPasswordField_Password;
    private javax.swing.JPasswordField jPasswordField_reTypePassword;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_FirstName;
    private javax.swing.JTextField jTextField_LastName;
    private javax.swing.JTextField jTextField_MiddleName;
    private javax.swing.JTextField jTextField_Number;
    // End of variables declaration//GEN-END:variables
}
